while true do 
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "DropMoney",
    [2] = "10000"
}

game:GetService("ReplicatedStorage").MainEvent:FireServer(unpack(args))
wait(1)
end